name: jfrog-oidc-repro

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  JF_URL: https://elinaf.jfrog.io

jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/setup-jfrog-cli@v5.0.0
        id: jfrog-auth
        with:
          oidc-provider-name: ronma
          oidc-audience: jf

