name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

# This is required as perc
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'github-oidc'
      PLATFORM_REPO: 'eks-npm'
     defaults:
      run:
        working-directory: ./package
     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}
           
       - name: Test JFrog Connection
         run: |
            # Enable debug logging
            export DEBUG=1
            export JFROG_CLI_LOG_LEVEL=DEBUG
            
            # Test connection
            jf rt ping
            jf docker login
            jf docker pull docker pull andreygra-noffarl-docker-remote.jfrog.io/hello-world     
