name: "Setup JFrog CLI OIDC Example2"
on: push

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: https://elinaf.jfrog.io
        with:
          # Name of the OIDC provider as specified on the OIDC integration page in the JFrog Platform
          oidc-provider-name: roin-oidc

      - name: Test JFrog Connection
        run: |
            # Enable debug logging
            export DEBUG=1
            export JFROG_CLI_LOG_LEVEL=DEBUG
            
            # Test connection
            jf rt ping
            jf docker login
            jf docker pull elinaf.jfrog.io/roin-docker-remote/library/hello-world
